# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e106c689c3f33fe592ff92c979922c533efa1c01bc9a64a987604e10ca340dc92b4dd73d4a79b5c17fd232c8af9061adc487f838fc0a2a48d692d5acb59aa27

test:
  secret_key_base: ed6e420ae5f5f8419c7d132fc9123de32a13f99ecb3900de3a39b712e1a97f52bf1e8cac94b586510d34c6a3538567b19027979ceb5abb57c255580657532063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
